Cam_weight: 200.0
CenterMap_weight: 160.0
FOV: 60
HMloss_type: MSE
MPJPE_weight: 200.0
PAMPJPE_weight: 360.0
PCK_thresh: 150
P_KP2D_weight: 400.0
Pose_weight: 80.0
Prior_weight: 1.6
Rot_type: 6D
Shape_weight: 6.0
Synthetic_occlusion_ratio: 0
add_offsetmap: true
adjust_lr_epoch: []
adjust_lr_factor: 0.2
baby_threshold: 0.8
backbone: hrnet
batch_size: 4
beta_dim: 10
bv_with_fv_condition: true
calc_PVE_error: true
calc_mesh_loss: true
calc_pck: false
calc_smpl_mesh: true
cam_dim: 3
cam_dist_thresh: 0.1
center_def_kp: true
centermap_conf_thresh: 0.2
centermap_size: 64
character: smpl
collision_aware_centermap: true
collision_factor: 0.2
color_jittering_ratio: 0.2
configs_yml: configs/v1_hrnet_flag3d_ft.yml
dataset: flag3d
dataset_rootdir: /home/yutao_intern/workspace/dataset/
deconv_num: 0
depth_loss_type: Piecewise
distillation_learning: false
distributed_training: false
epoch: 1
eval: false
eval_2dpose: false
eval_datasets: pw3d
f: null
fast_eval_iter: -1
fine_tune: true
fix_backbone_training_scratch: false
focal_length: 443.4
fps_save: 24
fv_conditioned_way: attention
gpu: 0
head_block_num: 2
homogenize_pose_space: false
hrnet_pretrain: /home/yutao_intern/workspace/ROMP-master/trained_models/pretrain_hrnet.pkl
image_loading_mode: image
input_size: 512
inputs: null
interactive_vis: false
kernel_sizes:
- 5
learn_2dpose: false
learn_AE: false
learn_kp2doffset: false
learn_relative: false
learn_relative_age: false
learn_relative_depth: false
learn_relative_shape: false
local_rank: 0
log_path: /home/yutao_intern/workspace/log/
loss_thresh: 1000
lr: 5.0e-05
make_tracking: false
master_batch_size: -1
match_preds_to_gts_for_supervision: true
matching_mode: all
matching_pckh_thresh: 0.6
max_person: 64
max_supervise_num: -1
merge_smpl_camera_head: false
mesh_cloth: '031'
model_path: /root/ROMP/trained_models/ROMP_HRNet32_V1.pkl
model_precision: fp16
model_return_loss: true
model_version: 1
multi_person: true
new_training: false
num_depth_level: 8
nvxia_model_path: /home/yutao_intern/workspace/ROMP-master/model_data/characters/nvxia
nw: 6
nw_eval: 2
optimizer_type: Adam
output_dir: null
perspective_proj: false
print_freq: 50
renderer: pytorch3d
resnet_pretrain: /home/yutao_intern/workspace/ROMP-master/trained_models/pretrain_resnet.pkl
rot_dim: 6
rotate_prob: 0.2
sample_prob_dict:
  flag3d: 1
sampling_aggregation_way: floor
save_dict_results: false
save_visualization_on_img: true
scale_anchor: true
show_largest_person_only: false
show_mesh_stand_on_image: false
shuffle_crop_mode: false
shuffle_crop_ratio_2d: 0.1
shuffle_crop_ratio_3d: 0.2
smil_model_path: /home/yutao_intern/workspace/ROMP-master/model_data/smpl_models/smil_packed_info.pth
smpl_joint_num: 22
smpl_mesh_root_align: true
smpl_model_path: /home/yutao_intern/workspace/ROMP-master/model_data/smpl_models/smpl_packed_info.pth
smpl_prior_path: /home/yutao_intern/workspace/ROMP-master/model_data/parameters/gmm_08.pkl
smpl_uvmap: /home/yutao_intern/workspace/ROMP-master/model_data/parameters/smpl_vt_ft.npz
smpla_model_path: /home/yutao_intern/workspace/ROMP-master/model_data/smpl_models/SMPLA_NEUTRAL.pth
soi_camera: far
supervise_cam_params: false
supervise_global_rot: false
surrounding_camera: false
tab: hrnet_cm64_V1_hrnet_flag3d_ft
teacher_model_path: /export/home/suny/CenterMesh/trained_models/3dpw_88_57.8.pkl
temporal_optimization: false
test_interval: 2000
top_n_error_vis: 6
track_memory_usage: false
use_coordmaps: true
use_eft: true
val_batch_size: 4
voc_dir: /home/yutao_intern/workspace/dataset/VOCdevkit/VOC2012/
wardrobe: /home/yutao_intern/workspace/ROMP-master/model_data/wardrobe
weight_decay: 1.0e-06
